
export const products = [
    {
        title: "Los Helechos Chardonnay",
        price: 4600,
        stock: 3,
        description: "Brillante, amarillo claro con reflejos dorados.<br>Nariz elegante y compleja, se destacan notas frutales y florales en perfecta comunión con suaves aromas de frutos secos y miel, logradas en su esmerada crianza en roble francés.<br>En boca entrada fresca y frutada de amplia y equilibrada acidez, su pensada crianza en barricas le otorga estructura y persistencia de sabores que llenan la boca y entregan un final largo y con carácter.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786644/ecommerce/thumb_62197_default_big_ew9qya.jpg",
        variety: "Chardonnay",
        manufacturingPlace: "Mendoza",
        genre: "Blanco",
        alcohol: 14.00,
        country: "Argentina",
        presentation: "750ml",
        producer: "Los Helechos"
    },
    {
        title: "Single Vineyard",
        price: 2500,
        stock: 2,
        description: "A la vista, presenta un color dorado, límpido y brillante.<br>En nariz, despliega complejos aromas que recuerdan a durazno, membrillo y cáscara de mandarina con sutiles notas de anís y flor de lima.<br>En boca es un vino amplio y untuoso con notas de damasco, manzana, miel y vainilla, otorgadas por su añejamiento en barricas de roble francés.Presenta un equilibrio perfecto entre dulzura y acidez, así como también un prolongado y elegante final.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786659/ecommerce/thumb_53622_default_big_kiiyss.jpg",
        variety: "Sauvignon Blanc",
        manufacturingPlace: "Finca La Pampa, Valle de Uco, Tunuyán. Provincia de Mendoza",
        genre: "Blanco",
        alcohol: 12.7,
        country: "Argentina",
        presentation: "750ml",
        producer: "Salentein"
    },
    {
        title: "Double Black",
        price: 18000,
        stock: 7,
        description: "Nariz llena de humo, especias inconfundibles y ligeros tonos de frutos secos.<br>Sabor ahumado y produce una intensa mezcla de extraordinaria profundidad y personalidad.<br>Johnnie Walker Double Black es un Whisky Blended añejado 12 años y elaborado de forma similar Johnnie Walker Black, el más conocido de sus hermanos, pero con un sabor ahumado más rico e intenso.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786668/ecommerce/thumb_60027_default_big_fdem6p.jpg",
        variety: "Whisky",
        manufacturingPlace: "Escocia",
        genre: "Blended",
        alcohol: 40.00,
        country: "Escocia",
        presentation: "750ml",
        producer: "Johnnie Walker"
    },
    {
        title: "Jack Daniels",
        price: 16700,
        stock: 0,
        description: "El color, cuerpo y sabor característico del Jack Daniels se debe a un minucioso proceso que lo hace único.<br>El whisky se realiza con agua subterránea sacada de una cueva en Tennessee, además al whisky se lo somete a un proceso llamado charcoal mellowing que consiste en filtrarlo a través de carbón de arce sacarino que lo convierte en lo que es: un Tennessee Whisky y no en un Bourbon, licor con el que se lo confunde por su suavidad a pesar de su alta graduación alcohólica.<br>Finalmente el whisky es añejado en barriles de roble blanco que son ensamblados a mano y quemados por dentro para fundir los azucares propios de la madera y darle al Jack Daniels su sabor y color ámbar.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786679/ecommerce/thumb_62442_default_big_hkh34m.jpg",
        variety: "Whisky",
        manufacturingPlace: "Tennesse",
        genre: "Bourbon",
        alcohol: 40.00,
        country: "Estados Unidos",
        presentation: "750ml",
        producer: "Jack Daniels"
    },
    {
        title: "Grolsch",
        price: 500,
        stock: 1,
        description: "Color dorado bastante profundo con una cabeza blanca.<br>En nariz hay presencia de lúpulo, notas vegetales picantes y un toque de pan tostado.<br>En el paladar hay un bonito juego entre lúpulo amargo y una cierta dulzura en el acabado, hay un buen apoyo a la nota de malta que añade peso.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786686/ecommerce/thumb_62637_default_big_cvotby.jpg",
        variety: "Rubia",
        manufacturingPlace: "Buenos Aires",
        genre: "Premium Lager",
        alcohol: 5.00,
        country: "Argentina",
        presentation: "473ml",
        producer: "Grolsch"
    },
    {
        title: "Beagle",
        price: 720,
        stock: 2,
        description: "La Cerveza Golden Ale es, como su nombre lo indica, de color dorado.<br>Tiene aroma a malta y fruta proveniente de la levadura tipo Ale, y es de cuerpo medio con complejos sabores a malta y lúpulos de la Patagonia.<br>De amargor medio, presenta una espuma blanca y persistente.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786700/ecommerce/thumb_67496_default_big_hbicza.jpg",
        variety: "Rubia",
        manufacturingPlace: "Ushuaia - Tierra del Fuego",
        genre: "Golden Ale",
        alcohol: 4.80,
        country: "Argentina",
        presentation: "330ml",
        producer: "Beagle"
    },
    {
        title: "Grey Goose",
        price: 35000,
        stock: 5,
        description: "Aroma: Claro, fresco, con un elegante aroma floral acentuado por una sutil nota cítrica. Sabor: Inicialmente suave con un dulzor que envuelve gradualmente la textura y redondea con un toque de almendra.<br>Final fresco, largo y satisfactorio.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786707/ecommerce/thumb_55765_default_big_tqwlwm.jpg",
        variety: "Vodka",
        manufacturingPlace: "Francia",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Francia",
        presentation: "700ml",
        producer: "Grey Goose"
    },
    {
        title: "Absolut Blue",
        price: 9600,
        stock: 9,
        description: "El primero de todos los Absolut, producido en 1979. Modo de consumo: Puro, con hielo o en tragos.<br>Es producido del trigo de invierno, un grano de trigo robusto que da su carácter de grano liso al vodka. Cada año aproximadamente 80,000 toneladas son usadas para producir el Vodka Absolut.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786714/ecommerce/thumb_67772_default_big_jfrayl.jpg",
        variety: "Vodka",
        manufacturingPlace: "Ahus",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Suecia",
        presentation: "700ml",
        producer: "Absolut"
    },
    {
        title: "Gordons",
        price: 3500,
        stock: 2,
        description: "Son apreciables con el gusto y el olfato el enebro, las fresas, los cítricos, y algunas hierbas y especias.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786731/ecommerce/thumb_65278_default_big_n0ku0s.jpg",
        variety: "Gin",
        manufacturingPlace: "Inglaterra",
        genre: "Destilados",
        alcohol: 37.50,
        country: "Inglaterra",
        presentation: "700ml",
        producer: "Gordons"
    },
    {
        title: "Bombay Sapphire",
        price: 10000,
        stock: 3,
        description: "El sabor de Bombay Sapphire es complejo, aromático, suave e insinuante. Tiene un sabor a cítricos maduros con un toque de enebro, combinado con un final elegante, ligero y especiado.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1686786743/ecommerce/thumb_52843_default_big_ufotcb.jpg",
        variety: "Gin",
        manufacturingPlace: "Warrington",
        genre: "Destilados",
        alcohol: 47.00,
        country: "Inglaterra",
        presentation: "750ml",
        producer: "Bombay Sapphire"
    },
    {
        title: "Vuelá Rosado",
        price: 2900,
        stock: 0,
        description: "El resultado es un vino de gran frescura e intensidad aromática, basado en elaboración por prensado y por sangrado de estas tres variedades.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689093667/ecommerce/thumb_59341_default_big_zzlcik.jpg",
        variety: "Pinot Gris",
        manufacturingPlace: "Los Chacayes, Valle de Uco, Mendoza",
        genre: "Rosado",
        alcohol: 13.00,
        country: "Argentina",
        presentation: "750ml",
        producer: "Piedra Negra"
    },
    {
        title: "Domingo Molina Torrontés",
        price: 6000,
        stock: 9,
        description: "Cosecha: Manual en cajas de 20 Kg. Fermentación: 5% del vino en barricas de roble francés y el resto en vasijas de acero inoxidable con temperatura controlada y levaduras seleccionadas. Maceración pelicular: NO. Tiempo de fermentación: 18 días. Temperatura de fermentación: 12º a 14º C. Fermentación maloláctica: NO.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689093717/ecommerce/thumb_54138_default_big_dajt8s.jpg",
        variety: "Torrontés",
        manufacturingPlace: "Valle de Cafayate. Provincia de Salta",
        genre: "Blanco",
        alcohol: 13.5,
        country: "Argentina",
        presentation: "750ml",
        producer: "Domingo Molina"
    },
    {
        title: "Glenmorangie Nectar Dor",
        price: 74000,
        stock: 11,
        description: "Jengibre, nuez moscada y almendras tostadas aportan un profundo y cálido sabor que se entremezcla con un toque de merengue de limón y miel de abeja.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689095935/ecommerce/thumb_61409_default_big_rotivf.jpg",
        variety: "Whisky",
        manufacturingPlace: "Tierras Altas",
        genre: "Single Malt",
        alcohol: 46.00,
        country: "Escocia",
        presentation: "700ml",
        producer: "Glenmorangie"
    },
    {
        title: "Grants Triple Wood",
        price: 6400,
        stock: 5,
        description: "Complejo, limpio con notas de pera madura y frutas de verano.<br>Equilibrada de vainilla con fragancias florales maltosas y ligeras.<br>Largo y dulce con sutil toque de humo.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689095934/ecommerce/thumb_63059_default_big_xtogt8.jpg",
        variety: "Whisky",
        manufacturingPlace: "Escocia",
        genre: "Blended",
        alcohol: 40.00,
        country: "Escocia",
        presentation: "750ml",
        producer: "Grants"
    },
    {
        title: "Amber Lager",
        price: 600,
        stock: 3,
        description: "Color: Ligero ámbar rojizo, de claridad brillante.<br>Aroma: Tostado ligero, por sus finas maltas.<br>Sabor: Cerveza con cuerpo pero a la vez delicada, de amargor apacible que permite dar a luz a un caramelo tostado delicioso.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689104671/ecommerce/thumb_63947_default_big_ybe49r.jpg",
        variety: "Roja",
        manufacturingPlace: "Valle del Río Negro. Provincia de Río Negro.",
        genre: "Lager",
        alcohol: 4.50,
        country: "Argentina",
        presentation: "410ml",
        producer: "Patagonia"
    },
    {
        title: "Corona",
        price: 330,
        stock: 12,
        description: "Corona es única porque tiene un color inconfundible, un sabor incomparable y en definitiva no tiene igual.<br>Si buscas momentos inolvidables Corona es sin duda para ti, porque todas y las más grandes experiencias están envasadas en la botella de la cerveza más famosa del mundo.<br>Corona es una cerveza clara que no esconde nada, de ahí su botella transparente.Y es que cuando se usan sólo los mejores ingredientes, no hay nada que ocultar.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689104670/ecommerce/thumb_66726_default_big_budbnb.jpg",
        variety: "Rubia",
        manufacturingPlace: "Argentina",
        genre: "Lager",
        alcohol: 4.50,
        country: "Argentina",
        presentation: "269ml",
        producer: "Corona"
    },
    {
        title: "Absolut Grapefruit",
        price: 1000,
        stock: 1,
        description: "Notas ricas y elegantes a pomelo rosado recién exprimido, levemente dulce y fresco.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689105848/ecommerce/thumb_67825_default_big_obwjpy.jpg",
        variety: "Vodka",
        manufacturingPlace: "Suecia",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Suecia",
        presentation: "700ml",
        producer: "Absolut"
    },
    {
        title: "Narciso Negro",
        price: 10000,
        stock: 0,
        description: "De color transparente límpido. Nariz con notas a malta dulce, con dejos a vainilla, algo meloso y de alcohol suave. Muy amable en boca, sedoso y dulce, con un final delicado y muy refrescante. Un Vodka para tomar solo o en cóctel.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689105851/ecommerce/thumb_67555_default_big_pa6k2d.jpg",
        variety: "Vodka",
        manufacturingPlace: "Las Compuertas, Lujan de Cuyo. Provincia de Mendoza",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Argentina",
        presentation: "1 Litro",
        producer: "Compañía Destilera Andina"
    },
    {
        title: "Flor de Sevilla",
        price: 9300,
        stock: 6,
        description: "Elaborado con naranjas de Sevilla, flores de azahar y otros cuatro botánicos, este gin presenta un color ámbar natural que rinde homenaje a la ciudad española que lleva su nombre y lo convierten en el compañero ideal para los atardeceres de la temporada con sus notas cítricas, afrutadas y vibrantes que envuelven el paladar y cautivan con su sabor.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689108523/ecommerce/thumb_63316_default_big_h9xzv2.jpg",
        variety: "Gin",
        manufacturingPlace: "Cameron Bridge",
        genre: "Destilados",
        alcohol: 41.30,
        country: "Escocia",
        presentation: "700ml",
        producer: "Tanqueray"
    },
    {
        title: "Mil Demonios",
        price: 6000,
        stock: 2,
        description: "Color: Incoloro, cristalino y transparente.<br>Nariz: Sorprendente armonía entre el cítrico refrescante y el enebro patagónico.<br>Boca: Redondo, primeramente aparece una sutil acidez que persiste por un tiempo y luego se descubre un retrogusto amargo gracias a las raíces utilizadas.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689108524/ecommerce/thumb_67997_default_big_tzxxtp.jpg",
        variety: "Gin",
        manufacturingPlace: "Provincia de Mendoza",
        genre: "Destilados",
        alcohol: 43.00,
        country: "Argentina",
        presentation: "750ml",
        producer: "Sin Reglas Wines"
    },
    {
        title: "Amalaya Malbec",
        price: 2000,
        stock: 7,
        description: "Brillante color rubí con bordes violetas.<br>Fresas, frambuesas y fruta madura con toque de pimienta y aromas de especias y elegantes notas florales.<br>En boca, sabores de fruta roja, especias y notas de vainilla de envejecimiento en roble francés.Muy buena frescura.Los taninos redondos y suaves conducen a un final delicado y persistente.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689093924/ecommerce/thumb_60937_default_big_kpxzph.jpg",
        variety: "Malbec",
        manufacturingPlace: "Finca Las Mercedes, Valle Calchaquí. Provincia de Salta.",
        genre: "Tinto",
        alcohol: 13.90,
        country: "Argentina",
        presentation: "750ml",
        producer: "Amalaya"
    },
    {
        title: "Don David Malbec",
        price: 2000,
        stock: 1,
        description: "Color: Color rojo vivaz con destellos violáceos y tonos de cereza. Lágrima noble.<br>Aroma: Mermeladas de ciruelas y pasas de uvas combinan con notas de tabaco de pipa, vainilla y tostado.<br>         Sabor: Vino equilibrado, con taninos dulces y suaves con notas de frutas secas y tabaco.Largo y agradable final.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689094109/ecommerce/thumb_52806_default_big_vopwcu.jpg",
        variety: "Malbec",
        manufacturingPlace: "Valle de Cafayate. Provincia de Salta.",
        genre: "Tinto",
        alcohol: 14.00,
        country: "Argentina",
        presentation: "750ml",
        producer: "El Esteco"
    },
    {
        title: "Sir Edwards",
        price: 6700,
        stock: 0,
        description: "La nariz: lo primero que nos viene a la nariz es olor a alcohol acompañado de manzana.<br>El paladar: posee un cuerpo ligero, pero no demasiado.Muy limpio.Encontraremos bastante madera pero sin eliminar los sabores acaramelados y dulces de este whisky.Se deja beber bien y es por esto que es un whisky muy recomendable para quienes empiezan.<br>El final: sin duda, lo mejor de este whisky.Tiene un final largo y afrutado donde también podréis encontrar vainilla, manzana, galletas y muy sutiles notas a pasas.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689095935/ecommerce/thumb_59726_default_big_sjckf4.jpg",
        variety: "Whisky",
        manufacturingPlace: "Escocia",
        genre: "Blended",
        alcohol: 40.00,
        country: "Escocia",
        presentation: "750ml",
        producer: "Sir Edwards"
    },
    {
        title: "100 Pipers",
        price: 3100,
        stock: 6,
        description: "Aroma de vainilla y caramelo con un toque de cítricos y de malta fresca.<br>Boca: Suave y cremoso, con un puñado de frutos secos y un poco de vainilla.<br>Acabado: Suave y volviéndose más picante con el tiempo.<br>En general, un blend bien elaborado.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689095935/ecommerce/thumb_55024_default_big_fk8hr6.jpg",
        variety: "Whisky",
        manufacturingPlace: "Escocia",
        genre: "Blended",
        alcohol: 40.00,
        country: "Escocia",
        presentation: "750ml",
        producer: "100 Pipers"
    },
    {
        title: "Amstel Premium",
        price: 400,
        stock: 2,
        description: "Color dorado bastante profundo con una cabeza blanca.<br>En nariz hay presencia de lúpulo, notas vegetales picantes y un toque de pan tostado.<br>En el paladar hay un bonito juego entre lúpulo amargo y una cierta dulzura en el acabado, hay un buen apoyo a la nota de malta que añade peso.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689104671/ecommerce/thumb_67694_default_big_xsyfme.jpg",
        variety: "Rubia",
        manufacturingPlace: "Santa Fé. Provincia de Santa Fé",
        genre: "Pilsener",
        alcohol: 4.70,
        country: "Argentina",
        presentation: "473ml",
        producer: "Amstel"
    },
    {
        title: "Blest IPA",
        price: 600,
        stock: 1,
        description: "Nuestra IPA, es de color ambar - rojizo, aportado por las maltas caramelizadas. Una característica, además del intenso amargor, es el aroma cítrico. Usamos lúpulos nacionales e importados.<br>En el sabor se mezclan notas terrosas, florales y leve a hierbas.El retrogusto queda invadivo por el amargor.<br>Si vas a disfrutarla con comidas, intentá que sean sabores fuertes, carnes ahumadas, picadas de sabores intensos.Ya que este estilo invadirá tus papilas gustativas y no te dejará saborear comidas delicadas.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689104671/ecommerce/thumb_67571_default_big_zk4t9y.jpg",
        variety: "Rubia",
        manufacturingPlace: "Bariloche",
        genre: "India Pale Ale",
        alcohol: 6.50,
        country: "Argentina",
        presentation: "355ml",
        producer: "Blest"
    },
    {
        title: "Smirnoff",
        price: 2000,
        stock: 3,
        description: "Color: Smirnoff Red es incoloro.<br>Olor: Aromas a chocolate y especias.<br>Sabor: Sabor suave y único.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689105846/ecommerce/thumb_52844_default_big_b88jwp.jpg",
        variety: "Vodka",
        manufacturingPlace: "Provincia de Buenos Aires",
        genre: "Destilados",
        alcohol: 37.50,
        country: "Argentina",
        presentation: "700ml",
        producer: "Smirnoff"
    },
    {
        title: "Belvedere",
        price: 30000,
        stock: 4,
        description: "Color: Cristalino y puro a la vista.<br>Aroma: Al olfato, es fresco y ligeramente dulce.Presenta aromas suaves cítricos, frutas, hierbas y vainilla.<br>Sabor: Al sabor es suave y cremoso.Predominan sabores como centeno, cítricos y vainilla.Suave y redondo hasta el final.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689105845/ecommerce/thumb_55763_default_big_z9j3fy.jpg",
        variety: "Vodka",
        manufacturingPlace: "Polonia",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Polonia",
        presentation: "700ml",
        producer: "Belvedere"
    },
    {
        title: "Sur",
        price: 5600,
        stock: 5,
        description: "Inspirado en Patagonia y en sus más finos botánicos, se destacan las notas de enebro, su carácter cítrico y fresco en nariz y una armoniosa complejidad en boca.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689108524/ecommerce/thumb_67820_default_big_dmougt.jpg",
        variety: "Gin",
        manufacturingPlace: "Argentina",
        genre: "Destilados",
        alcohol: 45.00,
        country: "Argentina",
        presentation: "700ml",
        producer: "Sur Gin"
    },
    {
        title: "The Botanist",
        price: 32500,
        stock: 16,
        description: "Este gin ultra premium se destila en Bruichladdich Distillery (Remy Cointreau) en la isla de Islay, en Escocia. Es la primera y única Dry Gin de la Isla de Islay.<br>En la elaboración de esta ginebra se utilizan 31 botánicos (9 no nativos propios de las ginebras clásicas y 22 silvestres y nativos de la isla recogidos a mano): raíz de angélica, mentha suaveolens o mastranzo, hoja de abedul, mirto, corteza de cassia, manzanilla (dulce), corteza de canela, flor de trébol (rojo), trébol (blanco), semillas de cilantro, flor de saúco, flor de tojo, flor del espino, flor de brezo, bayas de enebro, bayas de enebro (silvestres de la isla), galio, melisa, cáscara de limón, regaliz, ulmaria, artemisa, cáscara de naranja, raíz de lirio, menta, perifollo oloroso o cerifolio, tanaceto, cardo (rastrero), tomillo, menta de agua y salvia forestal.<br>El nombre de la ginebra proviene de la gran cantidad de ingredientes botánicos utilizados. En definitiva, se trata de una ginebra seca finamente sintonizada con aroma floral y enebro, apoyada con hierbas y especias.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689108525/ecommerce/thumb_58369_default_big_vzd0rf.jpg",
        variety: "Gin",
        manufacturingPlace: "Escocia",
        genre: "Destilados",
        alcohol: 46.00,
        country: "Escocia",
        presentation: "750ml",
        producer: "The Botanist"
    },
    {
        title: "Clos de los Siete",
        price: 4800,
        stock: 2,
        description: "Un blend de un rojo intenso con aromas a frutos rojos maduros y especias.<br>Posee taninos maduros que dan una sensación de redondez y una amplitud y final perdurables.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689094538/ecommerce/thumb_52808_default_big_zwjlan.jpg",
        variety: "Blend",
        manufacturingPlace: "Vistaflores - Tunuyán. Provincia de Mendoza.",
        genre: "Tinto",
        alcohol: 14.50,
        country: "Argentina",
        presentation: "750ml",
        producer: "Clos de los Siete"
    },
    {
        title: "Lamadrid Reserva Cabernet Franc",
        price: 3500,
        stock: 8,
        description: "De color rojo con tintes violetas.<br>Muy complejo en nariz, con aromas a pimiento rojo asado y cuero con un toque de vainilla y ahumados debido a su crianza de 14 meses en barrica.<br>En boca es untuoso, frutado y con buen balance.",
        category: "vinos",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689094715/ecommerce/thumb_58136_default_big_mmbhhh.jpg",
        variety: "Cabernet Franc",
        manufacturingPlace: "Agrelo, Luján de Cuyo. Provincia de Mendoza",
        genre: "Tinto",
        alcohol: 13.00,
        country: "Argentina",
        presentation: "750ml",
        producer: "Lamadrid"
    },
    {
        title: "Old Parr De Luxe",
        price: 11500,
        stock: 4,
        description: "De color dorado.<br>En nariz es limpio, ligero y fresco, con un toque de hojas verdes y flores, y notas de roble y tierra recién removida.<br>En boca, sabor de fruta madura, melocotones y frambuesas.Posee un final limpio y suave.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689095936/ecommerce/thumb_55269_default_big_ylk2jb.jpg",
        variety: "Whisky",
        manufacturingPlace: "Speyside",
        genre: "Blended",
        alcohol: 40.00,
        country: "Escocia",
        presentation: "750ml",
        producer: "Old Parr"
    },
    {
        title: "The Singleton 15 Años",
        price: 35000,
        stock: 15,
        description: "Ámbar profundo o naranja quemada.<br>Sensación ligeramente picante y seca, en general.Manzanas con caramelo y notas de panal de miel equilibradas por aceite de linaza y toques del mar.<br>Sin agua, el sabor es dulce al principio y luego seco en el acabado.Cálido, ligero y suave; tendiendo a delicado.Fruta fresca con notas picantes.<br>Seco.Peras y galletas digestivas, luego delicadamente especiado con notas a anís.",
        category: "whisky",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689095934/ecommerce/thumb_63319_default_big_alqjho.jpg",
        variety: "Whisky",
        manufacturingPlace: "Escocia",
        genre: "Single Malt",
        alcohol: 40.00,
        country: "Escocia",
        presentation: "700ml",
        producer: "The Singleton"
    },
    {
        title: "Cape Horn",
        price: 1200,
        stock: 0,
        description: "Generosamente lupulada, con una corona de espuma blanca que perdura en vaso, en aromas podemos sentir el lúpulo y hierbas con notas picantes en nariz.<br>Se percibe el aporte frutado de las levaduras Ale y notas de caramelo aportado por las maltas especiales.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689104672/ecommerce/thumb_66956_default_big_w4ngbs.jpg",
        variety: "Roja",
        manufacturingPlace: "Ushuaia. Provincia de Tierra del Fuego",
        genre: "India Pale Ale",
        alcohol: 6.50,
        country: "Argentina",
        presentation: "500ml",
        producer: "Cape Horn"
    },
    {
        title: "Cusqueña Dorada",
        price: 1300,
        stock: 6,
        description: "Cusqueña Dorada es la cerveza más apreciada de Perú. Su exquisito sabor y color dorado intenso se obtienen debido a un proceso especial de elaboración con triple filtrado.<br>El sabor y aroma que la distinguen se consiguen utilizando 100% malta de cebadas seleccionadas en combinación con el más fino lúpulo aromático.<br>La dedicación con la que está elaborada se refleja en su botella perfectamente labrada y una etiqueta inspirada por el misticismo de Machu Picchu, una de las maravillas del mundo.",
        category: "cerveza",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689104672/ecommerce/thumb_54697_default_big_lm1bh8.jpg",
        variety: "Rubia",
        manufacturingPlace: "Peru",
        genre: "Lager",
        alcohol: 5.00,
        country: "Peru",
        presentation: "330ml",
        producer: "Cusqueña"
    },
    {
        title: "Smirnoff Raspberry",
        price: 2000,
        stock: 5,
        description: "Color cristalino, claro como el agua.<br>Aromas de frambuesas con azúcar y gelatina de frambuesa pronunciada.<br>En boca es ligeramente dulce y de cuerpo medio, con sabores que recuerdan los aromas.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689105851/ecommerce/thumb_57264_default_big_bw4ghe.jpg",
        variety: "Vodka",
        manufacturingPlace: "Canadá",
        genre: "Destilados",
        alcohol: 35.00,
        country: "Canadá",
        presentation: "700ml",
        producer: "Smirnoff"
    },
    {
        title: "Skyy",
        price: 2800,
        stock: 3,
        description: "Color: Aspecto muy brillante, límpido y cristalino.<br>Olor: Pura neutralidad, con un 1° impacto de cebada pero apenas perceptible.<br>Sabor: Levemente astringente, cálido, de textura suave, con leve amargor.",
        category: "vodka",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689105845/ecommerce/thumb_54815_default_big_rmzuqk.jpg",
        variety: "Vodka",
        manufacturingPlace: "Estados Unidos",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Estados Unidos",
        presentation: "750ml",
        producer: "Skyy"
    },
    {
        title: "Heraclito 40",
        price: 8700,
        stock: 0,
        description: "Su composición cuenta con 40 Botánicos de dominante enebro y notas florales, armoniza las notas de cardamomo y coriandro que se desarrollan en esta bebida, luego de una salida compleja de cítricos que se balancean en esta sutil formula con un leve picante que evoca una postal de la India. Algunos de los botánicos utilizados son: Jengibre, eucalipto, comino, azahar, suico, manzanilla, malta pale ale, romero, jazmín, pomelo, aguaribay, regaliz, pepino, tamarindo, lemon grass, y incayuyo.",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689108524/ecommerce/thumb_67816_default_big_wdfjf4.jpg",
        variety: "Gin",
        manufacturingPlace: "Argentina",
        genre: "Destilados",
        alcohol: 46.00,
        country: "Argentina",
        presentation: "750ml",
        producer: "Heraclito & Macedonio"
    },
    {
        title: "Bulldog London Dry",
        price: 12500,
        stock: 1,
        description: "Su sabor es muy suave, apetecible y bien equilibrado. Cuenta con los botánicos clásicos como el limón, almendra, lavanda, enebro, cassia, angélica y regaliz, pero también con otros más exóticos como la amapola, las hojas de loto, el cilantro y el longan. Este último, también conocido como ojo de dragón, es una fruta exótica translúcida que suele emplearse en la medicina tradicional china y es probablemente el responsable de su aroma floral.<br>Una mezcla casi afrodisíaca, difícil de conseguir. Los botánicos se recolectan en la mejor época del año y siempre en el mismo lugar, por ejemplo, el limón se trae de Sevilla, el regaliz de Francia... Cuatro veces destilada y triple filtrada, es una ginebra fiel al estilo británico",
        category: "gin",
        img: "https://res.cloudinary.com/dcccntywe/image/upload/v1689108523/ecommerce/thumb_60924_default_big_j3dilv.jpg",
        variety: "Gin",
        manufacturingPlace: "Ingleterra",
        genre: "Destilados",
        alcohol: 40.00,
        country: "Inglaterra",
        presentation: "700ml",
        producer: "Bulldog"
    }
]